apiVersion: v1
name: cassandra
version: 0.15.4
appVersion: 3.11.6
description: Apache Cassandra is a free and open-source distributed database management
  system designed to handle large amounts of data across many commodity servers, providing
  high availability with no single point of failure.
  This chart is managed by Digitalis
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Cassandra_logo.svg/330px-Cassandra_logo.svg.png
keywords:
- cassandra
- database
- nosql
home: https://digitalis.io
engine: gotpl
