{{- if and .Values.serviceAccount.create .Values.serviceAccount.rules -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cassandra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{ toYaml .Values.serviceAccount.rules }}
{{- end -}}
